### ISSUE TITLE
Installing db Docker container fails

### ISSUE THREAD

**Issue by rdlester** [chrishenry/deltanyc-heatseek#102]
A GPG key fails to download or is out of date, and an error message appears stating "-y was used without specifying --force-yes".

Should we just add --force-yes to Dockerfile.mysql?

**Comment by chrishenry** [comment]
Was it related to [this issue](https://github.com/docker-library/mysql/issues/260), maybe?

**Comment by rdlester** [comment]
The error message is not the same; it looked more like: http://serverfault.com/questions/7145/what-should-i-do-when-i-got-the-keyexpired-error-message-after-an-apt-get-update

Anyways, a change adding --force-yes has been added to the repo, so this is fixed for now. This isn't really "good practice", however, so we should reevaluate at some point.
