### ISSUE TITLE
Properties are missing building number in street_address column

### ISSUE THREAD

**Issue by LKWLaLa** [chrishenry/deltanyc-heatseek#114]
In order for our property search to work with the Google API, we need to make sure street addresses have a building number to search by.  Currently, for example, the address `123 2nd Avenue` would appear as `2 Avenue` in the API, and cannot be found.

**Comment by rdlester** [comment]
Two parts here:
1. Some tables store the number and street in separate columns; it sounds like Properties import is ignoring that.
2. "2nd" v "2" is an address normalization problem. We should migrate to using [libpostal](https://github.com/openvenues/libpostal).

**Comment by rdlester** [comment]
Yup. Stuff was pulled in from hpd_buildings, which stores house number and street name separately.

**Comment by rdlester** [comment]
Pluto stores everything in a single field, but still has a few raw "2 AVENUE"s (27), so the issue won't be "gone", persay. These must be typos by whoever entered this stuff into Pluto originally.

123 2 AVENUE is now pulled in correctly to r_properties, so hpd_buildings is really the important one.
