### ISSUE TITLE
dob_violations rake task is failing with error message

### ISSUE THREAD

**Issue by LKWLaLa** [chrishenry/deltanyc-heatseek#127]
I've tried to run this connector twice, and it fails in the same place  (at about 100,00 + some imports):

```
rake aborted!/778261 
ActiveRecord::StatementInvalid: Mysql2::Error: Incorrect string value: '\xC2\x97\xC2\xBCNO...' for column 'disposition_comments' at row 1: INSERT INTO `r_dob_violations` (`property_id`, `isn_dob_bis_viol`, `violation_type`, `violation_category`, `issue_date`, `disposition_date`, `disposition_comments`, `created_at`, `updated_at`) VALUES (42843, '1153151', 'C-CONSTRUCTION', 'V*-DOB VIOLATION - DISMISSED', '2007-01-18 00:00:00', '2011-03-24 00:00:00', 'SINK HOLE AT S/W/C OF BLDG BACKFILLED,  LEVELED TO GRADE¼NO PRMT REQD¼OK TO DI', '2017-04-09 17:14:15', '2017-04-09 17:14:15')
/usr/local/bundle/gems/mysql2-0.4.5/lib/mysql2/client.rb:120:in `_query'
/usr/local/bundle/gems/mysql2-0.4.5/lib/mysql2/client.rb:120:in `block in query'
/usr/local/bundle/gems/mysql2-0.4.5/lib/mysql2/client.rb:119:in `handle_interrupt'
/usr/local/bundle/gems/mysql2-0.4.5/lib/mysql2/client.rb:119:in `query'
/usr/local/bundle/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract_mysql_adapter.rb:305:in `block in execute'
/usr/local/bundle/gems/activerecord-4.2.6/lib/active_record/connection_adapters/abstract_adapter.rb:472:in `block in log'
```

**Comment by rdlester** [comment]
db_connector:dob_violations seems to be a no-op for me right now. The subset of violations selected for in the task are no longer recorded in the same way; seems like they've chopped off everything but the violation code. To make things extra confusing, some violations store the code in the violation_type column, some in violation_type_code. Some rows also have null for significant numbers of columns.

**Comment by rdlester** [comment]
Actually, violation_type_code is what we really want to be selecting against.

The Socrata site shows proper values forr violation_type, but the csv I downloaded has only borked values.

**Comment by rdlester** [comment]
Works fine for me now.

**Comment by rdlester** [comment]
Never mind, I ran this before running the properties import by accident, making it a no-op.
