### ISSUE TITLE
HPD registrations structure has changed

### ISSUE THREAD

**Issue by chrishenry** [chrishenry/deltanyc-heatseek#136]
The `import_hpd_registrations.py` script needs to be updated to reflect the new structure.

**Comment by rdlester** [comment]
The columns in the downloaded data seems to match the columns in our script. Can you provide more detail?

This task is failing at the moment, but for a different reason (bad data causing import errors); see #148 .

**Comment by rdlester** [comment]
Pretty sure this is fixed by #156

**Comment by chrishenry** [comment]
Yep, confirmed by running with `--bust-disk-cache`
