### ISSUE TITLE
Join hpd_complaints and hpd_complaints_problems together in Rails front-end

### ISSUE THREAD

**Issue by rdlester** [chrishenry/deltanyc-heatseek#141]
HPD stores individual complaints separately from the various problems described in said complaints. We need to join these back together for our site.

**Comment by rdlester** [comment]
Once this is done, the front-end should be checked to ensure the complaint codes are being correctly joined together and producing real values (? should never be produced).

**Comment by chrishenry** [comment]
OK, I just dug into this a bit...

It's important to know that problems don't map cleanly to complaints. (There can be more than one problem to a complaint). I've broken this task out into 2 more issues;

* https://github.com/chrishenry/deltanyc-heatseek/issues/165
* https://github.com/chrishenry/deltanyc-heatseek/issues/166

We'll also need some design advice to handle situations where there is more than one problem.

**Comment by rdlester** [comment]
I think the simplest way to do it is simply show the problems as individual entries in the table that have the same timestamp / complaint in?

**Comment by rdlester** [comment]
This should be fixed by #169
