### ISSUE TITLE
Import hpd complaint problems into Rails

### ISSUE THREAD

**Issue by chrishenry** [chrishenry/deltanyc-heatseek#166]
Currently, we only import hpd complaints into the Rails app.

To show more information about the HPD complaints, we'll need to create a new table to store these, since there are many problems to a complaint.

**Comment by rdlester** [comment]
Seems like this should be super simple.

**Comment by nik-efimov-yyz** [comment]
@rdlester @chrishenry We'll need a new Rails DB table for this. I noticed that there aren't any DB migrations in the Rails app. How do you typically go about adding a table?

**Comment by rdlester** [comment]
No, we don't need a new Rails DB table. The existing `hpd_complaints` table
in Rails already has columns present for problem info, and the web page is
already set up with the assumption that the table lists problems as opposed
to individual complaints.

Re DB migrations: yes, we do use Rails DB migrations, please use those.
(Note that there is in fact a migration present, there's only just one at
the moment)

**Comment by chrishenry** [comment]
I'm fairly certain we do need a new table for this. Reason being, there appears to be a one to many relationship between complaints and problems. As in, a complaint can have many problems. The row counts in the DATA tables seem to confirm this.

**Comment by chrishenry** [comment]
Digging further, I found the description on the opendata site;

`
Each complaint is associated with one or more problems reported by the complainant. Problems are closed if a tenant verifies by phone that the condition was corrected or an inspection result is entered by an HPD inspector. A complaint is closed when all associated problems are closed
`

**Comment by nik-efimov-yyz** [comment]
@chrishenry I think I tend to agree with you, it's probably best to add a 2nd table for complaint problems, unless we don't care about presenting complaints at all and just present the list of problems that tenants reported.

**Comment by nik-efimov-yyz** [comment]
@rdlester I was thinking of working on this - adding the new table and changing the views a bit. Are you actively working on this?

**Comment by rdlester** [comment]
I don't really agree with this - why do we need to present the individual
complaints at all when the problems are what the user cares about?

**Comment by nik-efimov-yyz** [comment]
@rdlester My thinking is that they are semantically different and we need both to present the full picture. There are things on the Complaint level that are not set on the Problem level, like the apartment number. 

What we can do is change the logic of the db connector such that Complaints are never actually imported. We can just import the Problems, joining associated Complaints to populate fields missing from the Problem data, like the apartment number.

I guess we'd need to change the wording on the page a little bit as well since we'll be presenting Problems rather than Complaints.

cc @chrishenry

**Comment by nik-efimov-yyz** [comment]
Something like this (still untested):
```
    sql = "INSERT IGNORE INTO hpd_complaints
        (property_id, received_date, complaint_id, apartment, status, status_date, status_id,
        major_category, minor_category, description)
        SELECT prop.id, c.receiveddate, c.complaintid, c.apartment, p.status,
        p.statusdate, p.statusid, p.majorcategory, p.minorcategory, p.statusdescription
        FROM properties AS prop
        INNER JOIN #{ENV['MYSQL_DATABASE_DATA']}.hpd_complaints AS c ON prop.bbl = c.bbl
        INNER JOIN #{ENV['MYSQL_DATABASE_DATA']}.hpd_complaints_problems AS p ON p.complaintid = c.complaintid;"
```

**Comment by rdlester** [comment]
@nickefimov Yes, presenting the problems with useful information from the complaints is what I have in mind. The code you suggested is pretty much exactly the code in my PR, #169.

For now, #169 just uses the columns originally added to the Rails DB (type, majorcategoryid, minorcategoryid, codeid). However, I'm not really sure if, say, majorcategoryid is better for presentation than majorcategory. To make that decision, I need to see the actual data, but can't b/c of #165.
