### ISSUE TITLE
Unknown column 'bbl' in 'field list'

### ISSUE THREAD

**Issue by nik-efimov-yyz** [chrishenry/deltanyc-heatseek#168]
I started getting the following error when I run several py scripts since I pulled from master this morning.

```
mysql.connector.errors.ProgrammingError: 1054 (42S22): Unknown column 'bbl' in 'field list'
```
Triggered in `clean_utils.py` in `clean_bbl` I assume.

Has anyone experienced this?

**Comment by chrishenry** [comment]
Which scripts specifically? And would you mind posting the full stack trace?

**Comment by nik-efimov-yyz** [comment]
`import_hpd_buildings.py` is one of them. Basically, any script using `clean_bbl` method from `clean_utils.py`. I think I fixed it by changing the `column_exists` method from:
```
def column_exists(table, column, schema='deltanyc'):
```
to:
```
def column_exists(table, column, schema='deltanyc_data'):
```

**Comment by rdlester** [comment]
Whoops, default args strike again. This value really needs to be loaded from ENV. If the table name is never actually passed by callers, we can just drop that argument and pull in the name from ENV at the start of the function.
