### ISSUE TITLE
Add Mysql regex UDF to Docker setup

### ISSUE THREAD

**Issue by rdlester** [chrishenry/deltanyc-heatseek#34]
Two parts here:

1. Set up Docker instance to install https://github.com/mysqludf/lib_mysqludf_preg. There's a one-line command line install in the README; should just work out of the box on our instances (as PCRE is already installed).

2. Convert existing usage of regex_replace to preg_replace. The regex format is "perl" style (basically need to surround the regex with slashes); the column name goes last instead of first.

**Comment by chrishenry** [comment]
Resolved in https://github.com/chrishenry/deltanyc-heatseek/pull/38
