### ISSUE TITLE
Homepage: Show feedback after user has clicked go

### ISSUE THREAD

**Issue by chrishenry** [chrishenry/deltanyc-heatseek#40]
After searching for and selecting an address, clicking `[Go]` has a noticeable delay before the properties page is rendered. 

Show some feedback that the click was registered so that the user doesn't click multiple times.

**Comment by LKWLaLa** [comment]
I'm having a hard time replicating this delay on my end with seed data alone.  I'm happy to work on a progress bar feature, as well as a solution for issue #41 .  However, I think I need actual data from the imports in order to experience the same behavior on my end.
