### ISSUE TITLE
DOB Violations imported to Rails table have incorrect dates

### ISSUE THREAD

**Issue by chrishenry** [chrishenry/deltanyc-heatseek#44]
Currently, all dates for dob violations are `1900-01-01 00:00:00`.

I'm unsure if the problem is in the python import or the rake task.

**Comment by jpfreeley** [comment]
Sounds like python import, I believe that it is defaulted to that date if 
the import can't parse it. I will have a look a bit later.

**Comment by jpfreeley** [comment]
in utils.py line 214, if any date in the csv column does not conform to the
"date_format" the entire column becomes 1900-01-01 .. we need to figure out
how to check the value of each date in the column for conformity prior to
attempting the date conversion. we can "try" the date conversion and if
fails, then check individual date values. let me think on it a bit more.
