### ISSUE TITLE
Move hpd_complaints_prob into import scripts

### ISSUE THREAD

**Issue by chrishenry** [chrishenry/deltanyc-heatseek#50]
It might be from here.

https://github.com/chrishenry/deltanyc-heatseek/blob/master/JPF/postgres/postgres.skeleton.py#L808

**Comment by jpfreeley** [comment]
here ..
https://github.com/jpfreeley/deltanyc-heatseek/blob/master/JPF/mysql.skeleton.ipynb

**Comment by chrishenry** [comment]
Thanks @rdlester
