### ISSUE TITLE
error w/r/t 311.py in pandas/parser

### ISSUE THREAD

**Issue by LKWLaLa** [chrishenry/deltanyc-heatseek#52]
screen shots:

![image](https://cloud.githubusercontent.com/assets/15372198/21828574/34546e12-d75f-11e6-9ff1-4607433cc016.png)

![image](https://cloud.githubusercontent.com/assets/15372198/21828588/48812146-d75f-11e6-8742-0bd58257a087.png)

**Comment by rdlester** [comment]
I've run import-311.py successfully on my machine in Docker, so I'm pretty certain this is closed.

The second issue with AEP has also been fixed in #73.
