### ISSUE TITLE
error in import-aep.py

### ISSUE THREAD

**Issue by LKWLaLa** [chrishenry/deltanyc-heatseek#53]
screen shot:

![image](https://cloud.githubusercontent.com/assets/15372198/21830850/b6b1ba5a-d76d-11e6-8af4-de1cbf809d85.png)

**Comment by rdlester** [comment]
Your working directory needs to be the root of this repo when running this script - data/AEP_list.csv is a relative directory.

We should change this to build the absolute path of the data file, which can be determined given the absolute path of the script.
