### ISSUE TITLE
If address sent to /query returns no results, there's an error

### ISSUE THREAD

**Issue by chrishenry** [chrishenry/deltanyc-heatseek#56]
Instead of erroring, we should detect no results returned, and show an error message.

<img width="871" alt="screen-shot 2017-01-11 at 7 23 20 pm" src="https://cloud.githubusercontent.com/assets/35760/21871953/8117d5ac-d833-11e6-9f74-d251a9bd8b7d.png">

**Comment by LKWLaLa** [comment]
I'll work on this today.

**Comment by chrishenry** [comment]
👍 Confirmed
