### ISSUE TITLE
Error when executing docker-compose up - duplicate lib_mysqludf_preg_info 

### ISSUE THREAD

**Issue by LKWLaLa** [chrishenry/deltanyc-heatseek#61]
`db-udf_1  | ERROR 1125 (HY000) at line 3: Function 'lib_mysqludf_preg_info' already exists
deltanycheatseek_db-udf_1 exited with code 1`

**Comment by chrishenry** [comment]
Thanks for reporting! Thankfully, this error doesn't affect operation of the other containers.

This is a duplicate of https://github.com/chrishenry/deltanyc-heatseek/issues/39, closing.
