### ISSUE TITLE
Refactor: Replace all non-digit chars in clean_bbl

### ISSUE THREAD

**Issue by chrishenry** [chrishenry/deltanyc-heatseek#77]
We're currently replacing a few different characters in `clean_utils.clean_bbl` before consuming `block` and `lot` columns. We should just remove all non-digit characters.

**Comment by rdlester** [comment]
For @virgilib.

**Comment by rdlester** [comment]
The function to modify is at https://github.com/chrishenry/deltanyc-heatseek/blob/master/data-imports/clean_utils.py#L84

**Comment by virgilib** [comment]
@rdlester, in my commit on the pull request, I modified clean_bbl instead of the L84 you mentioned.  Let me know if I misunderstood the issue.

**Comment by chrishenry** [comment]
Hi @virgilib! You were definitely in the right place. (The line number shifted since the comment was made.)
