### ISSUE TITLE
Fill out installation details

### ISSUE THREAD

**Issue by rdlester** [chrishenry/deltanyc-heatseek#99]
Right now the README is light on install details.

We don't necessarily want to explain Docker, but do want to keep people from having to read the dockerfiles or scripts themselves.

**Comment by chrishenry** [comment]
What, specifically, are you looking for there? The point of using Docker is to not have to describe a lengthy install process.

It's definitely missing a section on what to do once Docker is up. (Running import scripts, rake db:setup, etc.)

**Comment by rdlester** [comment]
Yes, a section on what to do once Docker is up is exactly what I want to
add.

We should also link out to Docker, and maybe include additional
instructions / requirements for those who don't want to use Docker.
